### ISSUE TITLE
Archlinux AUR installation

### ISSUE THREAD

**Issue by Charon77** [nivekuil/rip#12]
Hi, I've added this package to [AUR](https://aur.archlinux.org/packages/rm-improved/) as `rm-improved` (due to name conflict with rip). Feel free to include installation instruction in your README.

Something like this:

### ArchLinux installation:
Package can be installed from AUR.
`$ yay -S rm-improved`

**Comment by nivekuil** [comment]
Hey, sorry for the delayed response -- thanks for taking the time to put up a PKGBUILD! I'll add it to the README. Might actually use the package myself :)
