### ISSUE TITLE
brew formula?

### ISSUE THREAD

**Issue by pshirshov** [nivekuil/rip#14]
Hi guys!

Thank you for this great tool. Could you create a homebrew formula please? (Custom tap would be fine too).

**Comment by knowler** [comment]
I plan on making a PR to the Homebrew repo for this. Just wondering in the maintainers would like the package to be called `rip` or `rm-improved`? I could need to be the former, though I haven’t found anywhere that would indicate that it couldn’t be the latter. I have the formula pretty much ready to go.

**Comment by nivekuil** [comment]
Thanks for doing this!  I don't have a personal preference, but one
point in favor of `rm-improved` is the precedent set by the Arch Linux
package.  Ultimately, it's your discretion.

**Comment by knowler** [comment]
Sounds good. I think I will follow the naming precedent set by the Arch package.
