### ISSUE TITLE
rip seems not to respect XDG_DATA_HOME

### ISSUE THREAD

**Issue by xkortex** [nivekuil/rip#16]
Fantastic tool! Works great overall, just one minor quibble: XDG_DATA_HOME seems to not work.

```
Linux 4.15.0-50-generic #54-Ubuntu x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

rip 0.12.0

```
I have XDG_DATA_HOME set to `/home/mike/.local/share`. Rip is still sending files to `/tmp/graveyard-mike`. 

Thanks!

**Comment by nivekuil** [comment]
Ah, I never published a release after merging the PR which added that feature
(couldn't publish on crates.io without emaail verification, couldn't verify
because.. apparently it got caught in the spam filter!)  Thanks for the report
:)

**Comment by xkortex** [comment]
Excellent, works great now!

I LOVE this tool by the way.
