### ISSUE TITLE
Issues when removing a symbolic link pointing to a directory

### ISSUE THREAD

**Issue by dclong** [nivekuil/rip#24]
When removing a symbolic link pointing to a directory, I expect `rip` to behave like `rm` which remove the symbolic link itself. However, `rip` removes the physical directory instead.

**Comment by nivekuil** [comment]
Can't repro on linux, it does and should just delete the symlink. Can you give more information about your setup?

Sep 1, 2021 7:19:46 PM Ben Chuanlong Du ***@***.***>:

**Comment by dclong** [comment]
I was working in a Ubuntu environment via Docker. It's odd. Seems that I couldn't reproduce it. Let's close this issue at this time. If it happens again, I will reopen it with more details.
