### ISSUE TITLE
Be argument-compatible with rm

### ISSUE THREAD

**Issue by AngusP** [nivekuil/rip#3]
rip's use of `-r` for resurrect as opposed to recursive delete may be confusing, and removes the possibility of aliasing rm to rip in the future

**Comment by bburdette** [comment]
I use rm -r all the time and it would be confusing to me.  What about -u instead of -r?  -u could stand for un-do or un-delete, fairly intuitive.

**Comment by nivekuil** [comment]
I hear you on the `-r` part: it's needlessly confusing, and I'll be changing it to '-u'. 

That being said, I consider removing the possibility of aliasing `rm` to `rip` more of a feature than a bug. Aliases aren't foolproof and `rm` should not be mistaken as anything other than the irreversibly dangerous command that it is.

**Comment by AngusP** [comment]
> That being said, I consider removing the possibility of aliasing rm to rip more of a feature than a bug. 

I'd agree that you should know what you're actually doing and not just alias `rm` to `rip` and be done with it, though for scripting purposes being able to run a script expecting rm with rip in it's place could be useful, especially it you don't particularly trust the script or know concretely what it does

**Comment by virtualritz** [comment]
Since this is implemented now, the issue could be closed with a reference to the resp. commit?
