### ISSUE TITLE
/tmp might be a partition with small free space

### ISSUE THREAD

**Issue by StefanoD** [nivekuil/rip#6]
What if /tmp is a partition with size x and you delete an file with size y and y > x?
What if /tmp would be big enough for y, but only free space of size m is left and m < y?

~/.trash seems to be more appropriate.

**Comment by nivekuil** [comment]
Assuming /tmp is on a different partition from the target, it would return some error for "not enough free space". You can certainly use `~/.trash` as the graveyard; see the notes section of the README.
